export const VersionNumbers = [
    {
        name:'8.999.89.1.216',
        payment_application_id:1
    },
    {
        name:'10.000.xx',
        payment_application_id:1
    },
    {
        name:'1.x.x-x',
        payment_application_id:2
    },
    {
        name:'3.1.0',
        payment_application_id:3
    },
    {
        name:'6',
        payment_application_id:4
    },
    {
        name:'3',
        payment_application_id:5
    },
    {
        name:'4',
        payment_application_id:5
    },
    {
        name:'V5',
        payment_application_id:5
    },
    {
        name:'6',
        payment_application_id:5
    },
    {
        name:'5',
        payment_application_id:6
    },
    {
        name:'2',
        payment_application_id:6
    },
    {
        name:'3',
        payment_application_id:6
    },
    {
        name:'1',
        payment_application_id:7
    },
    {
        name:'6',
        payment_application_id:7
    },
    {
        name:'1',
        payment_application_id:8
    },
    {
        name:'6',
        payment_application_id:8
    },
    {
        name:'1.3.1',
        payment_application_id:9
    },
    {
        name:'1',
        payment_application_id:10
    },
    {
        name:'1.1',
        payment_application_id:10
    },
    {
        name:'1.2',
        payment_application_id:10
    },
    {
        name:'1.3.X.X',
        payment_application_id:10
    },
    {
        name:'1.5.X.X',
        payment_application_id:10
    },
    {
        name:'1.4.X.X',
        payment_application_id:10
    },
    {
        name:'1.0.3.X',
        payment_application_id:11
    },
    {
        name:'1.0.3.X',
        payment_application_id:12
    },
    {
        name:'2.0.3.26',
        payment_application_id:13
    },{
        name:'2.0.5.0',
        payment_application_id:13
    },
    {
        name:'2.0.6.1',
        payment_application_id:13
    },
    {
        name:'2.0.6.3',
        payment_application_id:13
    },
    {
        name:'3.2.0.0',
        payment_application_id:14
    },
    {
        name:'3.2.0',
        payment_application_id:14
    },
    {
        name:'3.2.1.x',
        payment_application_id:14
    },
    {
        name:'3.2.2.x',
        payment_application_id:14
    },
    {
        name:'1.0.4.8',
        payment_application_id:15
    },
    {
        name:'1.0.5.x',
        payment_application_id:15
    },
    {
        name:'1.0.0.x',
        payment_application_id:16
    },
    {
        name:'1.0.1.x',
        payment_application_id:16
    },
    {
        name:'1.1.0.x',
        payment_application_id:16
    },
    {
        name:'1.1.1.x',
        payment_application_id:16
    },
    {
        name:'1.1.2.x',
        payment_application_id:16
    },
    {
        name:'1.1.3.x',
        payment_application_id:16
    },
] 